export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

// ---- ACTIONS IMMOBILI ----
export const LOAD_IMMOBILI_HOMEPAGE_SUCCESS = "LOAD_IMMOBILI_HOMEPAGE_SUCCESS";
export const RICERCA = "RICERCA";
export const RICERCA_SUCCESS = "RICERCA_SUCCESS";
export const LOAD_IMMOBILI_BY_ID = "LOAD_IMMOBILI_BY_ID";
export const LOAD_IMMOBILI_BY_ID_SUCCESS = "LOAD_IMMOBILI_BY_ID_SUCCESS";
export const LOAD_IMMOBILI_BY_ID_AND_DELETE_SUCCESS =
	"LOAD_IMMOBILI_BY_ID_AND_DELETE_SUCCESS";
export const LOAD_IMMOBILE = "LOAD_IMMOBILE";
export const LOAD_IMMOBILE_SUCCESS = "LOAD_IMMOBILE_SUCCESS";
export const PRENOTA_APPUNTAMENTO = "PRENOTA_APPUNTAMENTO";
export const PRENOTA_APPUNTAMENTO_SUCCESS = "PRENOTA_APPUNTAMENTO_SUCCESS";

// ---- ACTIONS UTENTE ----

export const GET_PROFILE_BY_TOKEN = "GET_PROFILE_BY_TOKEN";
export const GET_PROFILE_BY_TOKEN_SUCCESS = "GET_PROFILE_BY_TOKEN_SUCCESS";
export const REGISTRATION = "REGISTRATION";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS";
export const GET_APPUNTAMENTI = "GET_APPUNTAMENTI";
export const GET_APPUNTAMENTI_SUCCESS = "GET_APPUNTAMENTI_SUCCESS";

// ---- ACTIONS TOKEN ----
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

// ---- ACTIONS ERROR ----
export const CLEAR_ERROR_STATE = "CLEAR_ERROR_STATE";
export const ERROR_LOGIN = "ERROR_LOGIN";
export const ERROR_TOKEN = "ERROR_TOKEN";
export const ERROR_REGISTRATION = "ERROR_REGISTRATION";
export const ERROR_LOAD_IMMOBILE = "ERROR_LOAD_IMMOBILE";
export const ERROR_CHANGE_PASSWORD = "ERROR_CHANGE_PASSWORD";
export const ERROR_PRENOTA_APPUNTAMENTO = "ERROR_PRENOTA_APPUNTAMENTO";
