export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

// ---- ACTIONS IMMOBILI ----
export const LOAD_IMMOBILI_HOMEPAGE_SUCCESS = "LOAD_IMMOBILI_HOMEPAGE_SUCCESS";

// ---- ACTIONS UTENTE ----

export const GET_PROFILE_BY_TOKEN = "GET_PROFILE_BY_TOKEN";
export const GET_PROFILE_BY_TOKEN_SUCCESS = "GET_PROFILE_BY_TOKEN_SUCCESS";
export const REGISTRATION = "REGISTRATION";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";

// ---- ACTIONS TOKEN ----
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

// ---- ACTIONS ERROR ----
export const ERROR_LOGIN = "ERROR_LOGIN";
export const CLEAR_ERROR_STATE = "CLEAR_ERROR_STATE";
export const ERROR_TOKEN = "ERROR_TOKEN";
export const ERROR_REGISTRATION = "ERROR_REGISTRATION";
