export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

// ---- ACTIONS IMMOBILI ----
export const LOAD_IMMOBILI_HOMEPAGE_SUCCESS = "LOAD_IMMOBILI_HOMEPAGE_SUCCESS";

// ---- ACTIONS UTENTE ----
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

// ---- ACTIONS ERROR ----
export const ERROR_LOGIN = "ERROR_LOGIN";
export const CLEAR_ERROR_STATE = "CLEAR_ERROR_STATE";
